### ISSUE TITLE
[New Feature] Hololens support!

### ISSUE THREAD

**Issue by iBicha** [Unity-Technologies/experimental-ARInterface#33]
I've been thinking about implementing this for a while now. Since lots of people are dependant on this interface to create their cool AR experiences, it would be cool to be able to try it on the Hololens without adding a line of code.
For sure, the Hololens SLAM is way more sophisticated than ARKit/ARCore, which would make creating an interface fairly straight forward: 

1. The pose is pretty much automatic to get
2. Getting a cloudpoint would be through getting a mesh from a [SurfaceObserver ](https://docs.unity3d.com/ScriptReference/XR.WSA.SurfaceObserver.html) and returning the vertices as points
3. Planes can be inspired from [SpatialUnderstanding](https://github.com/Microsoft/MixedRealityToolkit/wiki/HoloToolkit.SpatialUnderstanding) and [SurfaceMeshesToPlanes ](https://github.com/kaorun55/HoloLens-Samples/blob/master/Unity/WorldAnchorDemo/Assets/HoloToolkit/SpatialMapping/Scripts/SurfaceMeshesToPlanes.cs)
4. Camera image can be retrieved with [PhotoCapture ](https://docs.unity3d.com/ScriptReference/XR.WSA.WebCam.PhotoCapture.html)

I kinda did the research to do this, but I thought to propose this and hear people out, if this is useful,  before diving in.
Cheers!

**Comment by stella3d** [comment]
I've thought about this myself !  in short, my thoughts are: 

it would probably work alright, but i don't think it's something we should do at this time.
there's a few reasons for this:

1) At Unity, we're actively working on fully-integrated cross platform APIs for this stuff.  I don't think that this code will or should be in use long enough to make HoloLens support worthwhile, because HoloLens support would be superseded by these new APIs.

2) While we can certainly get all the data needed from the HoloLens to support the interface, the HoloLens is quite a different device, with a different interaction paradigm, than mobile AR.  

With ARKit & ARCore, they offer many similar features, on devices with very similar interaction styles & specifications.  This means that bridging the technical platform gap is enough to enable many cross-platform experiences.  I don't think this would be enough in the case of the HoloLens and mobile AR - any cross platform experience there would require a significant amount of rework for the HoloLens.

3) HoloLens user base is small, and anybody who has developed HoloLens apps (I have, and i'm guessing you have too from the sound of it?) is probably used to a pretty different API.

I like how enthusiastic you are about the AR Interface - if you have a HoloLens device and are that curious, i would encourage you to give it a shot on your fork.  I'd certainly be interested to hear about how it goes if you do.

**Comment by stella3d** [comment]
In addition, were we to add support for HoloLens, we would need to do the work to properly modularize it. 
We don't want to make everyone who downloads the AR Interface download the hololens support code, due to the significantly smaller user percentage

**Comment by iBicha** [comment]
I can only say I agree with most of this! Sort of why I posted this issue before diving into it.
The idea was only to create the most minimalistic Hololens interface, just so people could test existing projects (with way better tracking, and without awkwardly holding the phone haha).

So in short, it's to try an ARKit/ARCore app running on Hololens, not to make an app for that works on both. (for example, Raycasting can be done with "gaze", and tapping a screen can be replaced with the pointer gesture, but not the other way around, because that's gonna be a lot of UX challenges...). Basically for fun.

But your second and third point, together makes it not so worth it I guess. This interface is interesting because people get to test something NOW with the interface, until Unity integrates a universal API for this (welp, this interface is over 4 months old, so that's not bad, it gave people time to experiment with cool AR tech before the official thing comes out), but most importantly I believe by making progress here (and especially mistakes) in experimental projects would help both game devs and Unity alike with planning ahead for the real thing.

Ps: I am enthusiastic not only about the AR Interface, but about Unity in general, and its mission to make game dev as accessible as possible to people. I became even more enthusiastic when I got to go to Unite Europe through [Unity without borders](https://unity3d.com/unity-without-borders), which was a heart warming gesture 😊 

I will keep this idea as a low priority project, and I'll give it a shot if I have free time or if I'm REALLY bored.
Thanks for your input @stella3d !
